### ISSUE TITLE
Window placement

### ISSUE THREAD

**Issue by sojusnik** [satran/fullscreenworkspace-satran.in#1] opened 2018-11-14 11:28 UTC
Let's assume that 4 workspaces are in use. Because they are "dynamic" (as opposed to "static"), Gnome always creates an additional empty one at the end. This will be our 5th workspace. If a window from one of those 4 workspaces goes into fullscreen mode, then it will be placed to the 6th workspace, instead of the 5th, that was empty before. Therefore we now have a still empty 5th workspace, then comes the 6th workspace with the fullscreen window and then at last the 7th empty workspace.

Could you improve your plugin that the fullscreen window will be placed to the 5th workspace instead of the 6th?

Many thanks in advance!

**Comment by satran** [comment] 2018-12-11 22:21
I'm not sure if I can reproduce this behaviour. When the application is moved to the 6th workspace, the 5th one is automatically removed. And also I believe it moves the fullscreen app to the 5th workspace. I'm running it on Gnome 3.30 on wayland(also on X) and this seems to be the behaviour. 

Could you provide me the Gnome version you are using.

**Comment by sojusnik** [comment] 2018-12-29 14:18
This happens on Ubuntu 18.10 with Gnome 3.30.1 with a Gnome X.org session.

**Comment by sojusnik** [comment] 2019-01-10 11:31
The [Auto Move Windows Extension](https://extensions.gnome.org/extension/16/auto-move-windows/) seems to cause this! If I disable it, then your extension works as expected.

To reproduce, install the extension, set f.i. your audio player to be opened on workspace 2, move all windows to workspace 1 and stay there, open the audio player (it should be opened in the background on workspace 2), then change into full screen mode while on workspace 1. The full screen window will be placed on workspace 4, not 3 (as it actually should be).

**Comment by stuaxo** [comment] 2020-05-05 12:52
Maybe make this so it checks if the last workspace is already empty, and use that instead of creating one if it's present ?

That way things should work, even if someone uses some extension that changes the behaviour so there isn't an empty workspace at the end).

**Comment by satran** [comment] 2020-05-23 10:00
@stuaxo pull requests are welcomed.

**Comment by satran** [comment] 2021-05-06 02:32
Closing this as won't fix.

**Closed by satran** 2021-05-06 02:32 UTC
